
#include <cstdio>

#include "Com.h"
#include "File.h"
#include "Stream.h"
#include "Tcp.h"


int main()
{
  /**
   * Se genera un array de punteros de la clase base que van a almacenar
   * instancias de las clases derivadas. Asi se comprueba como un puntero
   * a la clase base llama a los metodos virtuales sobreescritos por las
   * derivadas.
   */
  CStream* pStream[3];
  pStream[0] = new CFile();
  pStream[1] = new CCom();
  pStream[2] = new CTcp();

  printf("\n---\n");
  for (CStream* pIterator : pStream)
  {
    printf("\n---\n");
    pIterator->Open("Filename");
    pIterator->Read();
    pIterator->Write();
    pIterator->Close();
  }
  printf("\n---\n");


  /**
   * Como se ha definido el destructor de la clase base virtual, las
   * clases derivadas tambien ejecutan sus destructores antes de la
   * llamada al destructor base.
   */
  delete pStream[0];
  delete pStream[1];
  delete pStream[2];
  return 0;
}

/**
 * Salida:
Creando stream base...
Creando stream archivo...
Creando stream base...
Creando stream puerto serie...
Creando stream base...
Creando stream TCP...

---

---
Abriendo stream base...
Abriendo stream archivo...
Leyendo stream base...
Leyendo stream archivo...
Escribiendo stream base...
Escribiendo stream archivo...
Cerrando stream base...
Cerrando stream archivo...

---
Abriendo stream base...
Abriendo stream puerto serie...
Leyendo stream base...
Leyendo stream puerto serie...
Escribiendo stream base...
Escribiendo stream puerto serie...
Cerrando stream base...
Cerrando stream puerto serie...

---
Abriendo stream base...
Abriendo stream TCP...
Leyendo stream base...
Leyendo stream TCP...
Escribiendo stream base...
Escribiendo stream TCP...
Cerrando stream base...
Cerrando stream TCP...

---
Destruyendo stream archivo...
Destruyendo stream base...
Destruyendo stream puerto serie...
Destruyendo stream base...
Destruyendo stream TCP...
Destruyendo stream base...
 */